name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest-arm64, macos-latest]
        include:
          - os: ubuntu-latest-arm64
            build_script: build:executable:linux
            artifact_name: station-cli-linux-arm
          - os: macos-latest
            build_script: build:executable:macos
            artifact_name: station-cli-macos-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest-arm64" ]; then
            sudo apt-get update
            sudo apt-get install -y python3 make g++ git
          fi
          npm ci

      - name: Build executable
        run: npm run ${{ matrix.build_script }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: executables/${{ matrix.artifact_name }}
          if-no-files-found: error 